// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

package go_micro_srv_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 每条货轮的参数
type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwerId               string   `protobuf:"bytes,6,opt,name=ower_id,json=owerId,proto3" json:"ower_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwerId() string {
	if m != nil {
		return m.OwerId
	}
	return ""
}

// 等待运行的货物
type Specification struct {
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

// 货轮装的下的话，返回多条货轮信息
type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	Created              bool      `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor_04ef66862bb50716) }

var fileDescriptor_04ef66862bb50716 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xfe, 0xb7, 0x40, 0x29, 0xf3, 0x07, 0x0f, 0xe3, 0xc1, 0x15, 0x25, 0x69, 0x7a, 0xe2, 0x54,
	0x13, 0x88, 0x0f, 0x60, 0x4c, 0x48, 0xf4, 0x58, 0x8c, 0x1e, 0xc9, 0xb2, 0x1d, 0x71, 0x12, 0xda,
	0x6d, 0xda, 0xa6, 0xe0, 0x5b, 0xf8, 0x04, 0xbe, 0x81, 0xef, 0x68, 0xdc, 0x02, 0x06, 0xd3, 0xc0,
	0x69, 0x67, 0xbe, 0xf9, 0x66, 0xe6, 0x9b, 0x2f, 0x0b, 0x97, 0x59, 0x6e, 0x4a, 0x73, 0x53, 0x51,
	0x51, 0xd0, 0x6a, 0xfb, 0x84, 0x16, 0xc3, 0xf3, 0xa5, 0x09, 0x13, 0xd6, 0xb9, 0x09, 0x8b, 0xbc,
	0x0a, 0xeb, 0x52, 0xf0, 0x29, 0xc0, 0x7d, 0xb6, 0x21, 0x9e, 0x81, 0xc3, 0xb1, 0x14, 0xbe, 0x18,
	0xf5, 0x22, 0x87, 0x63, 0x1c, 0x80, 0xa7, 0x55, 0xa6, 0x34, 0x97, 0xef, 0xd2, 0xf1, 0xc5, 0xa8,
	0x13, 0xed, 0x73, 0x1c, 0x02, 0x24, 0x6a, 0x33, 0x5f, 0x13, 0x2f, 0xdf, 0x4a, 0xd9, 0xb2, 0xd5,
	0x5e, 0xa2, 0x36, 0x2f, 0x16, 0x40, 0x84, 0x76, 0xaa, 0x12, 0x92, 0x6d, 0x3b, 0xcc, 0xc6, 0x78,
	0x0d, 0x3d, 0x55, 0x29, 0x5e, 0xa9, 0xc5, 0x8a, 0x64, 0xc7, 0x17, 0x23, 0x2f, 0xfa, 0x05, 0xf0,
	0x02, 0xba, 0x66, 0x4d, 0xf9, 0x9c, 0x63, 0xe9, 0xda, 0x26, 0xf7, 0x27, 0x7d, 0x88, 0x83, 0x47,
	0xe8, 0xcf, 0x32, 0xd2, 0xfc, 0xca, 0x5a, 0x95, 0x6c, 0xd2, 0x03, 0x59, 0xad, 0xa3, 0xb2, 0x9c,
	0x3f, 0xb2, 0x82, 0x0f, 0x01, 0x5e, 0x44, 0x45, 0x66, 0xd2, 0x82, 0x70, 0x02, 0x6e, 0xed, 0x81,
	0x3d, 0xf9, 0xff, 0xf8, 0x2a, 0x6c, 0xf0, 0x27, 0xac, 0xbd, 0x89, 0xb6, 0x54, 0xbc, 0x85, 0x6e,
	0x1d, 0x15, 0xd2, 0xf1, 0x5b, 0xa7, 0xba, 0x76, 0x5c, 0x94, 0xd0, 0xd5, 0x39, 0xa9, 0x92, 0x62,
	0x2b, 0xd9, 0x8b, 0x76, 0xe9, 0xf8, 0x4b, 0x40, 0xbf, 0x66, 0xcf, 0x28, 0xaf, 0x58, 0x13, 0x3e,
	0x41, 0x7f, 0xca, 0x69, 0x7c, 0xb7, 0xb7, 0x26, 0x68, 0x5c, 0x71, 0x60, 0xca, 0x60, 0xd8, 0xc8,
	0xd9, 0xdd, 0x1a, 0xfc, 0xc3, 0x29, 0xb8, 0xf7, 0x76, 0x25, 0x1e, 0x53, 0x7c, 0x72, 0xce, 0xc2,
	0xb5, 0x7f, 0x69, 0xf2, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x0a, 0x38, 0xf4, 0x68, 0x02, 0x00,
	0x00,
}
